name: 'LEGO check in Automerge'

on:
  pull_request:
    types:
      - opened
    branches:
      - Localization

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'EzzhevNikita'
    steps:
      - uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.ABTT_TOKEN }}
          merge-method: squash
          pull-request: ${{ github.event.inputs.pull-request }}
