name: 'LEGO check in Automerge'

on:
  pull_request:
    types:
      - opened
    branches:
      - Localization

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'EzzhevNikita'
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: enhancement
          number: context.payload.pull_request.number
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ABTT_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
